from __future__ import annotations


HISTORICAL_STORIES: tuple[dict[str, object], ...] = (
    {
        "id": "story_history_2007_honda",
        "title": "绿箭队：节能赛车时代的起点",
        "published_date": "2007-11-11",
        "summary": "第一届 Honda 中国节能竞技大赛成绩资料中出现了燕山大学绿箭队，这是目前收录到的较早公开参赛记录。",
        "body": "这一阶段的公开资料为后来方程式车队的工程实践提供了早期线索。不同年份资料中曾出现“绿箭队”“绿能节能车队”等称呼，本条仅按原始成绩资料记录，不将不同名称强行视为同一组织。\n\n资料来源：第一届 Honda 中国节能竞技大赛成绩册\nhttps://www.honda.com.cn/uploads/upload/files/20250316/a6e3c55dc87aad68f3826c356bbd609d.pdf",
        "layout_style": "timeline",
    },
    {
        "id": "story_history_2010_yanxiang_1",
        "title": "燕翔一号：首届中国大学生方程式",
        "published_date": "2010-11-19",
        "summary": "燕山大学车队携燕翔一号参加首届中国大学生方程式汽车大赛，车队进入方程式赛车工程实践阶段。",
        "body": "公开报道记录了燕翔一号的设计、制造和参赛经历。这一赛季成为燕翔车队持续迭代赛车的重要起点。\n\n资料来源：燕山大学新闻网《我校燕翔车队在首届中国大学生方程式汽车大赛中取得佳绩》\nhttps://www.ysu.edu.cn/news/info/5504/10530.htm",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2011_public_view",
        "title": "从赛场走向大众视野",
        "published_date": "2011-10-07",
        "summary": "燕翔赛车与大学生方程式实践逐步进入校内外公开报道，车队文化开始形成更广泛的传播。",
        "body": "这一时期的校报资料保留了赛车实践、学生团队协作和赛事交流的历史切片。\n\n资料来源：燕山大学公开资料\nhttps://xxgk.ysu.edu.cn/_mediafile/dwzw/2014/09/18/2w21qukkg3.pdf",
        "layout_style": "editorial",
    },
    {
        "id": "story_history_2012_yanxiang_3",
        "title": "燕翔三号：比赛与国际展示",
        "published_date": "2012-10-29",
        "summary": "燕翔三号继续参加中国大学生方程式赛事，并成为车辆与能源学院对外展示学生工程实践的代表作品。",
        "body": "赛车项目把课堂知识、加工制造、调试验证和赛场协作连接起来，团队也通过公开活动展示阶段成果。\n\n资料来源：燕山大学新闻网\nhttps://www.ysu.edu.cn/news/info/5504/12320.htm\n\n资料来源：燕山大学车辆与能源学院\nhttps://vec.ysu.edu.cn/info/1002/1222.htm",
        "layout_style": "gallery",
    },
    {
        "id": "story_history_2013_workshop",
        "title": "旧仓库里的工程教育实践",
        "published_date": "2013-11-07",
        "summary": "公开报道聚焦车队在有限条件下完成设计、制造和调试的过程，记录了学生工程团队的成长环境。",
        "body": "车队的价值不仅体现在赛场名次，也体现在跨专业协作、反复验证和问题闭环。相关报道与校友资料保存了这一阶段的团队面貌。\n\n资料来源：科学网报道\nhttps://news.sciencenet.cn/sbhtmlnews/2013/11/279766.shtm\n\n资料来源：燕山大学校友资料\nhttps://xiaoyou.ysu.edu.cn/__local/9/05/BE/BC33AA6B3BBBE56548C13830F63_775664D0_BF512F.pdf",
        "layout_style": "editorial",
    },
    {
        "id": "story_history_2014_yanxiang_5",
        "title": "燕翔五号与创办高校奖",
        "published_date": "2014-10-18",
        "summary": "燕翔五号延续年度赛车迭代，相关校友资料记录了参赛成绩和创办高校奖等信息。",
        "body": "连续参赛使车队逐步建立设计传承、制造组织与赛后复盘机制。\n\n资料来源：燕山大学校友资料\nhttps://xiaoyou.ysu.edu.cn/__local/0/64/6B/65899350412218F8D097723C703_D09CA176_7442EC.pdf",
        "layout_style": "timeline",
    },
    {
        "id": "story_history_2015_national_fifth",
        "title": "全国第五名与一等奖",
        "published_date": "2015-10-17",
        "summary": "相关资料记录了车队取得全国第五名和一等奖，赛车工程能力与赛事表现进一步提升。",
        "body": "成绩背后是方案设计、加工装配、静态项目、动态项目和团队运营的共同结果。\n\n资料来源：燕山大学校友资料\nhttps://xiaoyou.ysu.edu.cn/__local/2/5E/EF/16A5D3B382ED02699C7869686AC_AA24F58B_342A9A2.pdf",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2016_yanxiang_7",
        "title": "燕翔七号：工程技术继续迭代",
        "published_date": "2016-09-29",
        "summary": "燕翔七号公开亮相，车队继续围绕整车设计、制造和赛事可靠性推进技术迭代。",
        "body": "公开报道呈现了新赛车发布与赛事准备过程，也记录了中国大学生方程式赛事当年的技术交流。\n\n资料来源：燕山大学新闻网\nhttps://www.ysu.edu.cn/news/yxsd/416.htm\n\n资料来源：荆楚网赛事报道\nhttps://www.cnhubei.com/xwzt/2016/dxsfcsqcds/qcdszx/201609/t3703110.shtml",
        "layout_style": "gallery",
    },
    {
        "id": "story_history_2017_yanxiang_8",
        "title": "燕翔八号：再次跻身全国第五",
        "published_date": "2017-11-23",
        "summary": "公开报道记录燕翔八号赛季及全国第五名成绩，车队保持了稳定的工程竞争力。",
        "body": "这一赛季既有赛事结果，也有校内公开活动资料，可共同用于回顾车队当年的技术和组织面貌。\n\n资料来源：搜狐公开报道\nhttps://www.sohu.com/a/206166414_661672\n\n资料来源：燕山大学通知资料\nhttps://notice.ysu.edu.cn/info/2009/2013.htm",
        "layout_style": "timeline",
    },
    {
        "id": "story_history_2018_yanxiang_9",
        "title": "燕翔九号：轻量化、数据采集与气动",
        "published_date": "2018-09-28",
        "summary": "燕翔九号相关资料展示了轻量化、数据采集和空气动力学等技术方向的持续投入。",
        "body": "车队的研发重点逐步从完成整车扩展到用数据和试验优化整车性能。\n\n资料来源：燕山大学教务处\nhttps://jwc.ysu.edu.cn/info/1088/1672.htm\n\n资料来源：新浪新闻公开报道\nhttps://www.sina.cn/news/detail/4330580352918487.html",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2019_first_ev",
        "title": "燕翔十号：首辆电动方程式赛车",
        "published_date": "2019-11-04",
        "summary": "燕山大学公开报道记录了燕翔十号及首辆电动方程式赛车，车队由燃油技术向电动技术拓展。",
        "body": "电动赛车带来了高压安全、电池系统、电机控制和整车电控等新的工程课题，也为后续三电技术积累建立基础。\n\n资料来源：燕山大学新闻网\nhttps://www.ysu.edu.cn/info/5415/13595.htm",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2021_yanxiang_12",
        "title": "吉利冠名与燕翔十二号",
        "published_date": "2021-11-24",
        "summary": "燕翔十二号赛季的公开资料记录了校企合作、赛车发布和新阶段的团队建设。",
        "body": "校企合作为人才培养、工程交流和赛事支持提供了新的连接方式。\n\n资料来源：燕山大学新闻网\nhttps://www.ysu.edu.cn/news/info/5502/14501.htm\n\n资料来源：中国青年网\nhttps://xibu.youth.cn/gzdt/gddt/202111/t20211124_13323507.htm",
        "layout_style": "editorial",
    },
    {
        "id": "story_history_2022_fsec",
        "title": "电动方程式全国第十三名",
        "published_date": "2022-06-24",
        "summary": "燕山大学公开报道记录车队在电动方程式赛事中取得全国第十三名。",
        "body": "这一成绩体现了电动赛车整车可靠性、安全规范和比赛执行能力的阶段成果。\n\n资料来源：燕山大学新闻网\nhttps://www.ysu.edu.cn/news/info/5504/15310.htm",
        "layout_style": "timeline",
    },
    {
        "id": "story_history_2023_e09",
        "title": "E09 与赛队公开技术档案",
        "published_date": "2023-11-17",
        "summary": "2023 年赛事手册收录了燕翔车队及 E09 赛车信息，为当年参赛阵容留下公开档案。",
        "body": "赛事手册是核对车号、参赛车队和赛事阶段信息的重要公开资料。\n\n资料来源：中国汽车工程学会 2023 FSEC/FSAC 赛事手册\nhttps://img.sae-china.org/web/2023/11/2023FSECFSAC%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8C%281%29.pdf",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2024_e36_a05",
        "title": "E36 与燕翔无人车队 A05",
        "published_date": "2024-10-26",
        "summary": "2024 年赛事资料记录了电动赛车 E36 与燕翔无人车队 A05，车队技术方向延伸至无人系统。",
        "body": "电动与无人方向并行发展，使整车电控、感知、规划和执行控制等能力进一步连接。\n\n资料来源：中国汽车工程学会 2024 FSEC 赛事手册\nhttps://img.sae-china.org/web/2024/10/2024FSEC%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8CHandbook%281%29.pdf\n\n资料来源：哔哩哔哩公开赛事视频\nhttps://www.bilibili.com/video/BV1H1sWeoEyL/",
        "layout_style": "gallery",
    },
    {
        "id": "story_history_2025_can_debug",
        "title": "2025 赛季：CAN 网络与整车调试",
        "published_date": "2025-10-01",
        "summary": "合作方公开访谈展示了车队在 CAN 网络、整车调试与赛事准备方面的实践。",
        "body": "公开访谈为理解当代学生车队的通信诊断、调试流程和工程协作提供了补充视角。\n\n资料来源：同星智能车队访谈\nhttps://www.tosunai.com/tosun-supports-2025-nio-cup-exclusive-interview-with-team-representative/",
        "layout_style": "technical",
    },
    {
        "id": "story_history_2026_international",
        "title": "国际交流、单体壳与无人系统",
        "published_date": "2026-08-27",
        "summary": "车辆与能源学院及公开社交平台资料记录了车队在国际交流、单体壳和无人系统方向的新进展。",
        "body": "这一阶段体现了车队在复合材料车身、智能驾驶与跨团队交流上的进一步探索。社交平台链接可能受平台登录和地区访问策略影响。\n\n资料来源：燕山大学车辆与能源学院\nhttps://vec.ysu.edu.cn/info/1002/8240.htm\n\n资料来源：微博公开内容（一）\nhttps://weibo.com/2/detail/5331471474365408\n\n资料来源：微博公开内容（二）\nhttps://weibo.com/2/detail/5336535794714847",
        "layout_style": "editorial",
    },
)
